/*

 BIKERSPRITES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Biker[] =
{
  0x18,0x00,0x18,0x00,0x10,0x02,0x18,0x06,
  0x10,0x6E,0x4A,0x52,0xA5,0xB5,0x42,0x42,
  0x00,0x00,0xC0,0x18,0xD0,0x0C,0x72,0x0A,
  0x1D,0x25,0x42,0x72,0xA0,0xA0,0x40,0x40
};

/* End of BIKERSPRITES.C */
